version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_dir: ~/project
    steps:
      - restore_cache:
          keys:
            - v0-repo-{{ .Branch }}-{{ .Revision }}
            - v0-repo-{{ .Branch }}
            - v0-repo
      - checkout
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/project.tar | true
      - run:
          name: Build docker image
          command: docker build -t project:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o ~/project.tar project:latest
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker tag project:latest developmentseed/openroads-vn-tiler:latest
              docker push developmentseed/openroads-vn-tiler:latest
            fi
