version: 2

jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
        environment:
          IMGNAME=developmentseed/openroads-vn-tiler
    working_dir: ~/project
    steps:
      - restore_cache:
          keys:
            - v0-repo-{{ .Branch }}-{{ .Revision }}
            - v0-repo-{{ .Branch }}
            - v0-repo
      - checkout
      - run:
          name: Get submodules
          command: git submodule update --recursive --init
      - save_cache:
          key: v0-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
      - setup_remote_docker
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i ~/project.tar | true
      - run:
          name: Build docker image
          command: docker build --cache-from=project -t $IMGNAME:latest .
      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o ~/project.tar $IMGNAME:latest
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              VERSION=$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker tag $IMGNAME:latest $IMGNAME:$VERSION
              docker push $IMGNAME
            fi
